scbcList = {
    'accenture':{'name':'Accenture','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Accenture_256x170.png'},
    'allstate':{'name':'All State','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Allstate_256x170-1.png'},
    'americanairlines':{'name':'American Airlines','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/AmericanAirlines_256x170.png'},
    'aon':{'name':'AON','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/AonColor.png'},
    'atnt':{'name':'AT&T','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/ATT_256x170.png'},
    'bankofamerica':{'name':'Bank of America','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/BOA_256x170.png'},
    'bestbuy':{'name':'Best Buy','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/BestBuy_256x170.png'},
    'borgwarner':{'name':'Borg Warner','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/BorgWarner_256x170.png'},
    'cisco':{'name':'Cisco','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Cisco_256x170.png'},
    'conedison':{'name':'Con Edison','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/ConEdison_256x170.png'},
    'cvs':{'name':'CVS Health','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/CVSHealth_256x170.png'},
    'deloitte':{'name':'Deloitte','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Deloitte_256x170.png'},
    'dickssportinggoods':{'name':'Dicks Sporting Goods','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Dicks_256x170.png'},
    'eaton':{'name':'Eaton','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Eaton_256x170.png'},
    'lilly':{'name':'Lilly','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Lilly_256x170.png'},
    'gap':{'name':'GAP','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Gap_256x170.png'},
    'gm':{'name':'General Motors','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/GM_256x170.png'},
    'homedepot':{'name':'The Home Depot','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/HomeDepot_256x170.png'},
    'indeed':{'name':'Indeed','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/indeed_256x170.png'},
    'jpmorgan':{'name':'JP Morgan & Chase Co.','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/JPMC_256x170.png'},
    'kelly':{'name':'Kelly','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Kelly_256x170.png'},
    'koch':{'name':'Koch Industries','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Koch_256x170-1.png'},
    'kroger':{'name':'Kroger','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Kroger_256x170.png'},
    'LKQ':{'name':'LKQ Corporation','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/LKQ_256x170.png'},
    'lowes':{'name':'Lowes\'s','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/LowesColor.png'},
    'macys':{'name':'Macy\'s','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Macys_256x170_2023-10-30-181736_aiio.png'},
    'mastercard':{'name':'MasterCard','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Mastercard_256x170.png'},
    'mcdonalds':{'name':'Mc Donald\'s','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/McDonalds_256x170_2021-04-20-185532.png'},
    'micron':{'name':'Micron','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Micron_256x170.png'},
    'microsoft':{'name':'Microsoft','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Microsoft_256x170.png'},
    'nba':{'name':'NBA','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/NBA_256x170.png'},
    'nbcuniversal':{'name':'NBC Universal','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Universal_256x170-2.png'},
    'png':{'name':'P&G','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/PG_256x170.png'},
    'paypal':{'name':'PayPal','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/PayPal_256x170.png'},
    'pepsico':{'name':'Pepsi Co.','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/PepsiCo_256x170.png'},
    'prudential':{'name':'Prudential','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Prudential_256x170.png'},
    'radiusrecycling':{'name':'Radius Recycling','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/RadiusRecycling_256x170.png'},
    'ralphlauren':{'name':'Ralph Lauren','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/RalphLauren_256x170.png'},
    'randstad':{'name':'Randstad','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Randstad_256x170.png'},
    'target':{'name':'Target','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Target_256x170.png'},
    'texasinstruments':{'name':'Texas Instruments','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/TexasInstruments_256x170.png'},
    'totalwine':{'name':'Total Wine','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/TotalWine_256x170.png'},
    'unionpacific':{'name':'Union Pacific','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/UnionPacific_256x170.png'},
    'united':{'name':'United Airlines','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/United_256x170.png'},
    'verizon':{'name':'Verizon','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/verizon.jpg'},
    'virgin':{'name':'Virgin','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Virgin_256x170.png'},
    'visa':{'name':'VISA','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Visa_256x170.png'},
    'vistra':{'name':'Vistra','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/Vistra_256x170.png'},
    'walgreensboots':{'name':'Walgreens','imgUrl':'https://www.walgreens.com/og-image.jpg'},
    'walmart':{'name':'Walmart','imgUrl':'https://brt-second-chance-production.s3.amazonaws.com/walmart.jpg'},
    'Amazon':{'name':'Amazon','imgUrl':'https://www.hatchwise.com/wp-content/uploads/2022/05/amazon-logo-1024x683.png'},
    'Chipotle':{'name':'Chipotle','imgUrl':'https://1000logos.net/wp-content/uploads/2021/04/Chipotle-logo.png'}
}

